// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxiJHclW2_4a9q02_zjX6bhs9pZliXHh0',
    appId: '1:1064616720221:web:15f237ed4556bd032a1ab4',
    messagingSenderId: '1064616720221',
    projectId: 'evo-nfc',
    authDomain: 'evo-nfc.firebaseapp.com',
    storageBucket: 'evo-nfc.appspot.com',
    measurementId: 'G-9YCY35GK4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzaxlEstuRucle-gBH0BlpTF3VFgNpx2s',
    appId: '1:1064616720221:android:23c0dcc4fc76ae772a1ab4',
    messagingSenderId: '1064616720221',
    projectId: 'evo-nfc',
    storageBucket: 'evo-nfc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCElmn9EolhI8HJ4MjKMjGfyc3WOqykQTk',
    appId: '1:1064616720221:ios:24961a22eeffa4f82a1ab4',
    messagingSenderId: '1064616720221',
    projectId: 'evo-nfc',
    storageBucket: 'evo-nfc.appspot.com',
    iosClientId: '1064616720221-1ot2vqahb5iplgrg9p9n6bc4pv0b9s75.apps.googleusercontent.com',
    iosBundleId: 'com.example.evoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCElmn9EolhI8HJ4MjKMjGfyc3WOqykQTk',
    appId: '1:1064616720221:ios:24961a22eeffa4f82a1ab4',
    messagingSenderId: '1064616720221',
    projectId: 'evo-nfc',
    storageBucket: 'evo-nfc.appspot.com',
    iosClientId: '1064616720221-1ot2vqahb5iplgrg9p9n6bc4pv0b9s75.apps.googleusercontent.com',
    iosBundleId: 'com.example.evoApp',
  );
}
